# Problem 2.5.5

## (a)

*A man has $4.55 in change composed entirely of dimes and quarters. What are the maximum and minimum number of coins that he can have? Is it possible for the number of dimes to equal the number of quarters?*

Since dimes are worth 10 cents and quarters are worth 25 cents, this situation corresponds to the linear diophantine equation $10x+25y=455$.

Check to see if there are solutions by seeing if $\gcd(10, 25) | 455$.

In [1]:
gcd(10, 25), rem(455, gcd(10, 25)) == 0

(5, true)

$\gcd(10, 25) = 5$ and $5 | 455$ so Burton Theorem 2.9 says that there are infinitely-many solutions. To find one of those solutions, use the Extended Euclidean Algorithm:

In [2]:
gcdx(10, 25)

(5, -2, 1)

This says that $5 = -2(10) + 1(25)$. Multiplying by 91 gives $455 = -182(10) + 91(25)$ so $x_0 = -182$ and $y_0 = 91$.

Theorem 2.9 also shows how to find all of the solutions given a particular solution. In this case, we find that $x = -182 + 5t$ and $y = 91 - 2t$ where $t$ is any integer. $x$ and $y$ are the *number* of coins, so the only solutions that make sense are when $x, y \ge 0$. Solving $-182 + 5t \ge 0$ and $91 - 2t \ge 0$, we find that $37 \le t \le 45$ (remembering that $t$ is an integer).

Before addressing the specific questions posed by this problem, I’d like to introduce code that implements the procedure I used to solve this and similar problems:

In [3]:
function theorem2_9(a, b, c)
  d, r, s = gcdx(a, b)
  rem(c, d) == 0 || throw(DomainError((a = a, b = b, c = c), "gcd($a, $b) = $d does not divide $c; so, no solutions to $(a)x + $(b)y = $c"))
  (
      x0 = r * c ÷ d,
      dx = b ÷ d,
      y0 = s * c ÷ d,
      dy = a ÷ d
  )
end

function diophantine(a, b, c)
  try
      solutions = theorem2_9(a, b, c)
      "$(a)x + $(b)y = $c has solutions x = $(solutions.x0) + $(solutions.dx)t, y = $(solutions.y0) − $(solutions.dy)t; t an integer"
  catch e
      e
  end
end

function diophantine(a, b, c, range)
  try
      solutions = theorem2_9(a, b, c)
      for t in range
          x = solutions.x0 + solutions.dx * t
          y = solutions.y0 - solutions.dy * t
          println((t = t, x = x, y = y))
      end
  catch e
      e
  end
end


diophantine (generic function with 2 methods)

This lets me get the computer to do the calculations so I can make more interesting mistakes:

In [4]:
diophantine(10, 25, 455)

"10x + 25y = 455 has solutions x = -182 + 5t, y = 91 − 2t; t an integer"

It also lets me explore solutions once I’ve worked out an appropriate range for $t$:

In [5]:
diophantine(10, 25, 455, 37:45)

(t = 37, x = 3, y = 17)
(t = 38, x = 8, y = 15)
(t = 39, x = 13, y = 13)
(t = 40, x = 18, y = 11)
(t = 41, x = 23, y = 9)
(t = 42, x = 28, y = 7)
(t = 43, x = 33, y = 5)
(t = 44, x = 38, y = 3)
(t = 45, x = 43, y = 1)


Going back to the questions for this problem; the number of coins is minimum when the number of quarters is largest: 3 dimes and 17 quarters; 20 coins. Conversely, the number of coins is maximum when the number of dimes is largest: 43 dimes and one quarter; 44 coins. We could solve $-182 + 5t = 91 - 2t$ to find that the number of coins can be equal when $t = 39$ (13 dimes, 13 quarters), but it’s easier to find it in the results above.

## (b)

*The neighborhood theater charges $1.80 for adult admissions and $.75 for children. On a particular evening the total receipts were $90. Assuming that more adults than children were present, how many people attended?*

In [6]:
diophantine(180, 75, 9000)

"180x + 75y = 9000 has solutions x = -1200 + 5t, y = 3000 − 12t; t an integer"

Restricting solutions to $-1200 + 5t \ge 0$, $3000 - 12t \ge 0$ and $-1200 + 5t > 3000 - 12t$ we find that $t$ can be $248$ or $249$.

In [7]:
diophantine(180, 75, 9000, 248:249)

(t = 248, x = 40, y = 24)
(t = 249, x = 45, y = 12)


So, either 64 ($40 + 24$) or 57 ($45 + 12$) people attended.

## (c)

*A certain number of sixes and nines is added to give a sum of 126; if the number of sixes and nines is interchanged, the new sum is 114. How many of each were there originally?*

In [8]:
diophantine(6, 9, 126)

"6x + 9y = 126 has solutions x = -42 + 3t, y = 42 − 2t; t an integer"

In [9]:
diophantine(9, 6, 114)

"9x + 6y = 114 has solutions x = 38 + 2t, y = -38 − 3t; t an integer"

We would like to know when $x_a = x_b$ and $y_a = y_b$ where $a$ and $b$ are the first and second sums. This leads to $-42 + 3t_a = 38 + 2t_b$ and $42 - 2t_a = -38 - 3t_b$. I’m sure I could solve these two equations in two unknowns if I spent enough effort remembering how to do that, but why don’t I just look at the solutions when the numbers of sixes and nines are positive. (a reasonable interpretation of, “a certain number of …”)

In [10]:
diophantine(6, 9, 126, 15:20)

(t = 15, x = 3, y = 12)
(t = 16, x = 6, y = 10)
(t = 17, x = 9, y = 8)
(t = 18, x = 12, y = 6)
(t = 19, x = 15, y = 4)
(t = 20, x = 18, y = 2)


In [11]:
diophantine(9, 6, 114, -18:-13)

(t = -18, x = 2, y = 16)
(t = -17, x = 4, y = 13)
(t = -16, x = 6, y = 10)
(t = -15, x = 8, y = 7)
(t = -14, x = 10, y = 4)
(t = -13, x = 12, y = 1)


There it is: 6 sixes and 10 nines equals 126, and 6 nines and 10 sixes is 114.